### PR TITLE
V1.2

### PR DESCRIPTION
**Pull request by rakow**

### CODE REVIEW

**Comment by rakow** [comment]
@simei94 @GregorRyb could you add a test for [ParkingLocation.java](https://sonarcloud.io/component_measures?id=matsim-scenarios_matsim-leipzig&branch=v1.2&metric=new_coverage&selected=matsim-scenarios_matsim-leipzig%3Asrc%2Fmain%2Fjava%2Forg%2Fmatsim%2Fanalysis%2FParkingLocation.java). Test coverage should be good then.

**Comment by tschlenther** [comment]
@rakow @GregorRyb 
is this PR ready to be merged?
This PR shows changes in 52 files and a lot of committs... Seems to me like we should be carfeul not to let `main` diverge much more...

**Comment by rakow** [comment]
This includes all changes for the v1.2 release. Of course, it has a lot of changes. Main is the stable branch. This branch was originally based on the new parking approach.

**Comment by rakow** [comment]
You are right that it includes a lot of changes, which is not ideal. But a lot of it was not stable and unfinished most of the time.

**Pull request merged**
