### PR TITLE
Speed reduction

### PR DESCRIPTION
**Pull request by GregorRyb**

### CODE REVIEW

**Comment by simei94** [comment]
I think we now should merge this into master. I adapted the filtering mode (car -> bike) for the relative speed change as there is the possibility to run speed reduction combined with a car free scenario, which means that for a speed reduction + car free area scenario for many links the speed wont change as they do not have car as an allowed mode

**Comment by rakow** [comment]
Please fix the remaining style issues before merging.

**Comment by simei94** [comment]
Right now I have to take back my statement from yesterday, that we should merge this branch. There was a merge main->this branch yesterday (4.4.23, @GregorRyb), which altered some features which were implemented on this branch. The ones I noticed were:
1. run param for relative speed in RunLeipzigScenario.class does not exist anymore.
2. Class which applies the speed reduction on the network is named Tempo30Zone.class again (it was re-named to SpeedReduction.class)

There may be more errors. So we have to figure out everything what went wrong because of this merge and fix it I'd say. After that we can figure out the remaining style issues and merge into main.

**Comment by rakow** [comment]
I removed all of Gregors changes already and merged it again. Please check again if everything is as supposed now.

**Pull request merged**
